// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2_tlxCt_SzFVysw58cMt4dcmdPJSWepI',
    appId: '1:29947398865:web:ce33e00efc4971efe9d3f0',
    messagingSenderId: '29947398865',
    projectId: 'vault-99bd4',
    authDomain: 'vault-99bd4.firebaseapp.com',
    storageBucket: 'vault-99bd4.firebasestorage.app',
    measurementId: 'G-6510JZNXW4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArAneRug9zvUrRCsI_oGrz_LHsKMmcmqo',
    appId: '1:29947398865:ios:da3fcee8c12a9011e9d3f0',
    messagingSenderId: '29947398865',
    projectId: 'vault-99bd4',
    storageBucket: 'vault-99bd4.firebasestorage.app',
    iosBundleId: 'com.example.docusenseAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArAneRug9zvUrRCsI_oGrz_LHsKMmcmqo',
    appId: '1:29947398865:ios:da3fcee8c12a9011e9d3f0',
    messagingSenderId: '29947398865',
    projectId: 'vault-99bd4',
    storageBucket: 'vault-99bd4.firebasestorage.app',
    iosBundleId: 'com.example.docusenseAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2_tlxCt_SzFVysw58cMt4dcmdPJSWepI',
    appId: '1:29947398865:web:852648b985a7fe39e9d3f0',
    messagingSenderId: '29947398865',
    projectId: 'vault-99bd4',
    authDomain: 'vault-99bd4.firebaseapp.com',
    storageBucket: 'vault-99bd4.firebasestorage.app',
    measurementId: 'G-CJ4TJFE3JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXkfWcENInor6OpUBBWHR7PjNiPN8Ay_U',
    appId: '1:29947398865:android:9f8690f5b888dd05e9d3f0',
    messagingSenderId: '29947398865',
    projectId: 'vault-99bd4',
    storageBucket: 'vault-99bd4.firebasestorage.app',
  );

}